DROP TABLE IF EXISTS tasks CASCADE;

CREATE TABLE tasks (
  id SERIAL PRIMARY KEY NOT NULL,
  list_id INTEGER REFERENCES lists(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  is_completed? BOOLEAN NOT NULL DEFAULT FALSE,
  deadline DATE
);