DROP TABLE IF EXISTS actions CASCADE;

CREATE TABLE actions (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  action_name VARCHAR(255) NOT NULL,
  date_created DATE DEFAULT CURRENT_DATE,
  is_completed BOOLEAN DEFAULT FALSE
);