DROP TABLE IF EXISTS logDatas CASCADE;

CREATE TABLE logDatas (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id VARCHAR(255) NOT NULL,
  date_created DATE DEFAULT CURRENT_DATE,
  is_completed BOOLEAN DEFAULT FALSE
);